# Generated by Django 4.2.6 on 2023-10-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaty_salon', '0002_alter_postmodel_img_secpi1_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='master/')),
                ('text_n', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
